### ISSUE TITLE
Spelling Error I noticed

### ISSUE THREAD

**Issue by NagusameCS** [MAYKELL07/Web-Dashboard#1]
Hi, sorry, I just noticed a Spelling error and figured I should let you know.

<img width="858" alt="Screenshot 2023-11-15 at 4 59 24 p m" src="https://github.com/MAYKELL07/Web-Dashboard/assets/150973942/4385f0b8-4650-4d33-9bc7-8951aca35c9e">

As you can see Upgrade was misspelled as Updrade

**Comment by MAYKELL07** [comment]
Thanks for the info
